CREATE TABLE IF NOT EXISTS schedule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    pwd VARCHAR(255),
    todo VARCHAR(255),
    createdAt VARCHAR(255) DEFAULT CURRENT_TIMESTAMP,
    updatedAt VARCHAR(255) DEFAULT CURRENT_TIMESTAMP
    );